[package]
name = "helloWorld"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.140"
anyhow = "1.0.98"
